# The name of the current backend
name: "PMFKG-Kviz"
# The icon of the backend. Supported values are [png, jpg, svg, null]
icon: null
# All courses of the current backend
courses:
  - OOP-Java
support_url: https://discord.gg/by9wC55xJ7
body: |
  PMFKG-Kviz backend
